import { User, Category, Activity, Goal, UserPreferences } from '../types';
import { toDateString } from './dateUtils';

export const DEMO_USERS: User[] = [
  {
    id: 'user_alex',
    name: 'Alex Chen',
    email: 'alex.chen@chronicle.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'Founder & Senior Architect',
    plan: 'pro',
    onboarded: true,
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'user_elena',
    name: 'Dr. Elena Rostova',
    email: 'elena.rostova@neuroscience.org',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'Cognitive Neuroscientist',
    plan: 'pro',
    onboarded: true,
    createdAt: '2026-02-01T09:30:00.000Z',
  },
  {
    id: 'user_new',
    name: 'Jordan Miller',
    email: 'jordan@freshstart.dev',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'Product Designer',
    plan: 'free',
    onboarded: false, // will trigger onboarding flow
    createdAt: '2026-09-07T10:00:00.000Z',
  },
];

export const DEFAULT_PREFERENCES: UserPreferences = {
  is24Hour: true,
  startWeekOnMonday: true,
  defaultView: 'dashboard',
  soundEffects: true,
  theme: 'dark',
  calendarNumberFont: 'geometric',
};

export const ALEX_CATEGORIES: Category[] = [
  { id: 'cat_deep_work', name: 'Deep Work', color: '#6366f1', icon: 'Code2', defaultDurationMinutes: 90, isSystem: true },
  { id: 'cat_fitness', name: 'Fitness & Health', color: '#10b981', icon: 'Dumbbell', defaultDurationMinutes: 60, isSystem: true },
  { id: 'cat_architecture', name: 'System Design', color: '#3b82f6', icon: 'Cpu', defaultDurationMinutes: 75, isSystem: true },
  { id: 'cat_strategy', name: 'Product Strategy', color: '#ec4899', icon: 'Compass', defaultDurationMinutes: 45, isSystem: false },
  { id: 'cat_learning', name: 'Reading & Learning', color: '#f59e0b', icon: 'BookOpen', defaultDurationMinutes: 45, isSystem: false },
  { id: 'cat_admin', name: 'Comms & Admin', color: '#64748b', icon: 'Mail', defaultDurationMinutes: 25, isSystem: false },
  { id: 'cat_wellness', name: 'Recovery & Mind', color: '#06b6d4', icon: 'HeartPulse', defaultDurationMinutes: 20, isSystem: false },
];

export const ELENA_CATEGORIES: Category[] = [
  { id: 'cat_lab', name: 'Neuro Lab & Imaging', color: '#8b5cf6', icon: 'FlaskConical', defaultDurationMinutes: 120, isSystem: true },
  { id: 'cat_paper', name: 'Manuscript Writing', color: '#3b82f6', icon: 'FileText', defaultDurationMinutes: 60, isSystem: true },
  { id: 'cat_yoga', name: 'Yoga & Movement', color: '#14b8a6', icon: 'Activity', defaultDurationMinutes: 45, isSystem: true },
  { id: 'cat_mentor', name: 'PhD Mentoring', color: '#f97316', icon: 'Users', defaultDurationMinutes: 45, isSystem: false },
  { id: 'cat_grants', name: 'NIH Grant Proposals', color: '#e11d48', icon: 'Briefcase', defaultDurationMinutes: 90, isSystem: false },
];

export const STARTER_CATEGORIES: Category[] = [
  { id: 'cat_work', name: 'Work', color: '#6366f1', icon: 'Briefcase', defaultDurationMinutes: 60, isSystem: true },
  { id: 'cat_exercise', name: 'Exercise', color: '#10b981', icon: 'Activity', defaultDurationMinutes: 45, isSystem: true },
  { id: 'cat_study', name: 'Learning', color: '#f59e0b', icon: 'BookOpen', defaultDurationMinutes: 45, isSystem: true },
  { id: 'cat_personal', name: 'Personal', color: '#ec4899', icon: 'Smile', defaultDurationMinutes: 30, isSystem: true },
];

export function getAlexSeedActivities(): Activity[] {
  const now = new Date();
  
  // Helper to generate past dates relative to today
  const getDateOffset = (offsetDays: number) => {
    const d = new Date(now);
    d.setDate(now.getDate() - offsetDays);
    return toDateString(d);
  };

  const today = getDateOffset(0);
  const yesterday = getDateOffset(1);
  const dayMinus2 = getDateOffset(2);
  const dayMinus3 = getDateOffset(3);
  const dayMinus4 = getDateOffset(4);
  const dayMinus5 = getDateOffset(5);
  const dayMinus6 = getDateOffset(6);
  const dayMinus7 = getDateOffset(7);
  const dayMinus8 = getDateOffset(8);
  const dayMinus9 = getDateOffset(9);

  return [
    // Today
    {
      id: 'act_101',
      userId: 'user_alex',
      title: 'Morning 5K Interval Run & Core Routine',
      description: 'Tempo run in the park followed by 15 mins mobility and core stretches.',
      categoryId: 'cat_fitness',
      date: today,
      startTime: '06:45',
      endTime: '07:45',
      durationMinutes: 60,
      status: 'completed',
      tags: ['running', 'morning-routine', 'cardio'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_102',
      userId: 'user_alex',
      title: 'Distributed Event Bus Migration Spec',
      description: 'Wrote the RFC for upgrading event pipeline from RabbitMQ to Kafka partition clusters with zero downtime.',
      categoryId: 'cat_architecture',
      date: today,
      startTime: '08:30',
      endTime: '10:15',
      durationMinutes: 105,
      status: 'completed',
      tags: ['architecture', 'kafka', 'rfc'],
      energyLevel: 'high',
      attachmentUrl: 'https://github.com/org/rfc-event-bus',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_103',
      userId: 'user_alex',
      title: 'Building WebSocket Connection Pooling Hook',
      description: 'Implemented heartbeat reconnects, binary buffer deduplication, and exponential backoff.',
      categoryId: 'cat_deep_work',
      date: today,
      startTime: '10:30',
      endTime: '12:45',
      durationMinutes: 135,
      status: 'completed',
      tags: ['typescript', 'react', 'networking'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_104',
      userId: 'user_alex',
      title: 'Q3 Enterprise Pricing & Seat Model Review',
      description: 'Analyzed unit economics, customer churn per tier, and drafted self-serve upgrade flows.',
      categoryId: 'cat_strategy',
      date: today,
      startTime: '14:00',
      endTime: '15:15',
      durationMinutes: 75,
      status: 'completed',
      tags: ['pricing', 'saas', 'strategy'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_105',
      userId: 'user_alex',
      title: 'Read: Designing Data-Intensive Applications (Ch. 9)',
      description: 'Consistency guarantees, linearizability vs serializability, and 2-phase commit trade-offs.',
      categoryId: 'cat_learning',
      date: today,
      startTime: '16:00',
      endTime: '16:50',
      durationMinutes: 50,
      status: 'completed',
      tags: ['books', 'distributed-systems'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },

    // Yesterday
    {
      id: 'act_201',
      userId: 'user_alex',
      title: 'Heavy Strength Training (Deadlift & Shoulders)',
      description: 'Pyramid sets up to 180kg deadlift. Accessory work with overhead presses.',
      categoryId: 'cat_fitness',
      date: yesterday,
      startTime: '07:00',
      endTime: '08:15',
      durationMinutes: 75,
      status: 'completed',
      tags: ['gym', 'strength'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_202',
      userId: 'user_alex',
      title: 'Refactor Query Cache Engine in Go Backend',
      description: 'Reduced heap allocations by 34% by switching to pre-allocated byte slices for redis keys.',
      categoryId: 'cat_deep_work',
      date: yesterday,
      startTime: '09:00',
      endTime: '11:45',
      durationMinutes: 165,
      status: 'completed',
      tags: ['golang', 'performance', 'deep-work'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_203',
      userId: 'user_alex',
      title: 'Customer Advisory Call: Fintech Scale-Up',
      description: 'Discussed API rate limit requirements and enterprise audit log compliance.',
      categoryId: 'cat_strategy',
      date: yesterday,
      startTime: '13:30',
      endTime: '14:30',
      durationMinutes: 60,
      status: 'completed',
      tags: ['customers', 'discovery'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_204',
      userId: 'user_alex',
      title: 'Weekly Triage & Dependency Patching',
      description: 'Reviewed security Dependabot PRs and cleared urgent Zendesk tickets.',
      categoryId: 'cat_admin',
      date: yesterday,
      startTime: '15:00',
      endTime: '15:45',
      durationMinutes: 45,
      status: 'completed',
      tags: ['maintenance', 'admin'],
      energyLevel: 'low',
      createdAt: new Date().toISOString(),
    },

    // 2 Days Ago
    {
      id: 'act_301',
      userId: 'user_alex',
      title: 'Full-Stack Performance Profiling',
      description: 'Traced slow database indexes and eliminated 4 N+1 queries in the dashboard query graph.',
      categoryId: 'cat_deep_work',
      date: dayMinus2,
      startTime: '09:15',
      endTime: '12:00',
      durationMinutes: 165,
      status: 'completed',
      tags: ['postgres', 'optimization'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_302',
      userId: 'user_alex',
      title: 'HIIT Kettlebell Session & Sauna',
      description: '30 min kettlebell EMOM followed by 20 min sauna recovery.',
      categoryId: 'cat_fitness',
      date: dayMinus2,
      startTime: '12:30',
      endTime: '13:30',
      durationMinutes: 60,
      status: 'completed',
      tags: ['hiit', 'sauna', 'recovery'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_303',
      userId: 'user_alex',
      title: 'Product Design Sprint: Activity Timeline Layout',
      description: 'Explored wireframes for calendar day view and responsive mobile quick entry drawer.',
      categoryId: 'cat_strategy',
      date: dayMinus2,
      startTime: '15:00',
      endTime: '17:00',
      durationMinutes: 120,
      status: 'completed',
      tags: ['figma', 'ux', 'product'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },

    // 3 Days Ago
    {
      id: 'act_401',
      userId: 'user_alex',
      title: 'System Health Check & Kubernetes Autoscaler Tuning',
      description: 'Configured HPA metrics and CPU/memory request bounds for production pods.',
      categoryId: 'cat_architecture',
      date: dayMinus3,
      startTime: '08:30',
      endTime: '11:00',
      durationMinutes: 150,
      status: 'completed',
      tags: ['k8s', 'infra', 'devops'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_402',
      userId: 'user_alex',
      title: 'Read: Vector Embeddings & Index Quantization',
      description: 'Paper on HNSW graph construction and IVF-PQ compression techniques.',
      categoryId: 'cat_learning',
      date: dayMinus3,
      startTime: '14:00',
      endTime: '15:30',
      durationMinutes: 90,
      status: 'completed',
      tags: ['ai', 'papers', 'algorithms'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },

    // 4 to 9 Days Ago
    {
      id: 'act_501',
      userId: 'user_alex',
      title: 'Refactored Authentication Session Management',
      description: 'Implemented sliding session expiry with encrypted token rotation.',
      categoryId: 'cat_deep_work',
      date: dayMinus4,
      startTime: '09:00',
      endTime: '12:30',
      durationMinutes: 210,
      status: 'completed',
      tags: ['security', 'auth'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_502',
      userId: 'user_alex',
      title: 'Barbell Squat & Mobility Session',
      description: 'Heavy 5x5 squats + hamstring accessories.',
      categoryId: 'cat_fitness',
      date: dayMinus4,
      startTime: '13:30',
      endTime: '14:45',
      durationMinutes: 75,
      status: 'completed',
      tags: ['gym', 'legs'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_601',
      userId: 'user_alex',
      title: 'Database Sharding Proof of Concept',
      description: 'Benchmarked Vitess vs Citus for multi-tenant tenant isolation scaling.',
      categoryId: 'cat_architecture',
      date: dayMinus5,
      startTime: '09:30',
      endTime: '12:30',
      durationMinutes: 180,
      status: 'completed',
      tags: ['databases', 'citus'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_701',
      userId: 'user_alex',
      title: 'Long Distance Trail Run (12K)',
      description: 'Elevation gain 340m through forest trails.',
      categoryId: 'cat_fitness',
      date: dayMinus6,
      startTime: '07:30',
      endTime: '09:00',
      durationMinutes: 90,
      status: 'completed',
      tags: ['running', 'endurance'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_801',
      userId: 'user_alex',
      title: 'Writing Technical Blog Post: Distributed Tracing',
      description: 'Drafted deep-dive guide on OpenTelemetry spans in async microservices.',
      categoryId: 'cat_learning',
      date: dayMinus7,
      startTime: '10:00',
      endTime: '12:15',
      durationMinutes: 135,
      status: 'completed',
      tags: ['writing', 'opentelemetry'],
      energyLevel: 'medium',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_901',
      userId: 'user_alex',
      title: 'Architecture Review: Multi-Region Failover',
      description: 'Drill scenario testing DNS health routing and Aurora global database replication lag.',
      categoryId: 'cat_architecture',
      date: dayMinus8,
      startTime: '11:00',
      endTime: '13:00',
      durationMinutes: 120,
      status: 'completed',
      tags: ['aws', 'resilience'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'act_902',
      userId: 'user_alex',
      title: 'Full Body Kettlebell Complex',
      description: 'Clean and presses, snatches, and goblet squats.',
      categoryId: 'cat_fitness',
      date: dayMinus9,
      startTime: '07:30',
      endTime: '08:30',
      durationMinutes: 60,
      status: 'completed',
      tags: ['kettlebell', 'fitness'],
      energyLevel: 'high',
      createdAt: new Date().toISOString(),
    },
  ];
}

export const ALEX_GOALS: Goal[] = [
  {
    id: 'goal_1',
    userId: 'user_alex',
    title: 'Deep Engineering Focus',
    categoryId: 'cat_deep_work',
    targetType: 'hours',
    targetValue: 15,
    period: 'weekly',
    color: '#6366f1',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'goal_2',
    userId: 'user_alex',
    title: 'Strength & Cardio Routine',
    categoryId: 'cat_fitness',
    targetType: 'count',
    targetValue: 4,
    period: 'weekly',
    color: '#10b981',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'goal_3',
    userId: 'user_alex',
    title: 'Books & Technical Papers',
    categoryId: 'cat_learning',
    targetType: 'hours',
    targetValue: 4,
    period: 'weekly',
    color: '#f59e0b',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'goal_4',
    userId: 'user_alex',
    title: 'System Architecture Design',
    categoryId: 'cat_architecture',
    targetType: 'hours',
    targetValue: 8,
    period: 'weekly',
    color: '#3b82f6',
    createdAt: '2026-08-01T00:00:00.000Z',
  },
];
